/**
 * Example
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param type 
 * @param mediaKey 
 * @param height 
 * @param width 
 */

interface Media : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    @Json(name = "type")
    val type: kotlin.String
    @Json(name = "media_key")
    val mediaKey: kotlin.String?
    @Json(name = "height")
    val height: kotlin.String?
    @Json(name = "width")
    val width: kotlin.String?
}

