/**
 * Example
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param bitRate The bit rate of the media
 * @param contentType The content type of the media
 * @param url The url to the media
 */

data class VideoAllOfVariants (

    /* The bit rate of the media */
    @Json(name = "bit_rate")
    val bitRate: kotlin.Int? = null,

    /* The content type of the media */
    @Json(name = "content_type")
    val contentType: kotlin.String? = null,

    /* The url to the media */
    @Json(name = "url")
    val url: java.net.URI? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

